---
abstract: '(mostly) Non-global use/require cycle detection'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Simple: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cycle-Detect
provides:
  Cycle::Detect:
    file: lib/Cycle/Detect.pm
    version: 0.002
requires:
  Carp: 0
resources:
  bugtracker: http://github.com/exodist/Cycle-Detect/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Cycle-Detect
version: 0.002
